# debug与否
debug: false
# 开启在端口：
server:
  port: 8080
file:
  upload:
    path: D:/zcfun-data/
im:
  keys:
    online-user-set: online_users
spring:
  application:
    name: zcfun
  # 设置文件上传限制
  servlet:
    multipart:
      max-file-size: 444MB
      max-request-size: 444MB
      resolve-lazily: true
  # mysql设置
  datasource:
    url: jdbc:mysql://localhost:3306/zcfun
    password: ddivhutaow1fevki
    username: root
  # rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  # redis设置
  data:
    redis:
      host: localhost
      port: 6379
  # jackson设置
  jackson:
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: true
    time-zone: Asia/Shanghai
# mybatis设置
mybatis:
  configuration:
    use-column-label: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml
# hutool设置
snowflake:
  worker-id: 1
  datacenter-id: 1
jwt:
  key: ee044392420d89b41081a267f3672935
