# debug与否
debug: true
# 开启在端口：
server:
  port: 8080
spring:
  application:
    name: zcfun
  # 设置文件上传限制
  servlet:
    multipart:
      max-file-size: 2GB
      max-request-size: 2GB
  # mysql设置
  datasource:
    url: jdbc:mysql://localhost:3306/zcfun
    password: ddivhutaow1fevki
    username: root
  # rabbitmq配置
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /
  # redis设置
  data:
    redis:
      host: localhost
      port: 6379
  # 日期格式，但不生效（哭）
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
# mybatis设置
mybatis:
  configuration:
    use-column-label: true
    map-underscore-to-camel-case: true
  mapper-locations: classpath:mapper/**/*.xml


# hutool设置
snowflake:
  worker-id: 1
  datacenter-id: 1
jwt:
  key: "ee044392420d89b41081a267f3672935"
